// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testcase1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testcase1() {
    driver.get("https://www.air.irctc.co.in/");
    driver.manage().window().setSize(new Dimension(850, 752));
    driver.findElement(By.id("stationFrom")).click();
    driver.findElement(By.id("ui-id-28")).click();
    driver.findElement(By.id("stationFrom")).sendKeys("Hyderabad (HYD)");
    driver.findElement(By.id("ui-id-63")).click();
    driver.findElement(By.id("stationTo")).sendKeys("Pune (PNQ)");
    driver.findElement(By.cssSelector(".active-red")).click();
    driver.findElement(By.id("noOfpaxEtc")).click();
    driver.findElement(By.id("travelClass")).click();
    {
      WebElement dropdown = driver.findElement(By.id("travelClass"));
      dropdown.findElement(By.xpath("//option[. = 'Business']")).click();
    }
    driver.findElement(By.cssSelector(".home-btn")).click();
  }
}
